"""
PropDAO Trading Engine - Models & Data Structures
=================================================
Defines core data structures, enums, risk states, trade orders, positions,
and trade outcomes adhering to the PropDAO v1 API reference.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Dict, Any, List
import time


class OrderDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"

    @classmethod
    def from_direction(cls, direction: OrderDirection | str) -> OrderSide:
        d = str(direction).upper()
        if "LONG" in d or d == "BUY":
            return cls.BUY
        return cls.SELL

    def to_direction(self) -> OrderDirection:
        return OrderDirection.LONG if self == OrderSide.BUY else OrderDirection.SHORT


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_MARKET = "stop_market"
    STOP_LIMIT = "stop_limit"
    TAKE_MARKET = "take_market"
    TAKE_LIMIT = "take_limit"
    SCALE = "scale"
    TWAP = "twap"


class TimeInForce(str, Enum):
    GTC = "gtc"  # Good 'til cancelled (default)
    IOC = "ioc"  # Immediate or cancel (market orders only)
    ALO = "alo"  # Add liquidity only / post-only


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    TRIGGERED = "TRIGGERED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"


class TWAPState(str, Enum):
    AWAITING_TRIGGER = "AWAITING_TRIGGER"
    RUNNING = "RUNNING"
    TERMINATED = "TERMINATED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class AccountStatus(str, Enum):
    ACTIVE = "active"      # Evaluation stage in progress
    FUNDED = "funded"      # Successfully passed evaluation and funded
    PASSED = "passed"      # Passed challenge
    FAILED = "failed"      # Breached drawdown
    EXPIRED = "expired"    # Expired challenge


class Stage(str, Enum):
    EVALUATION = "Evaluation"
    FUNDED = "Funded"


class FloorKind(str, Enum):
    MAX = "max"          # Static drawdown floor (e.g. 5% below initial balance)
    DAILY = "daily"      # Daily loss limit floor (e.g. 1%, 2% or 3% below 00:00 UTC anchor equity)


class TradeReason(str, Enum):
    MANUAL_CLOSE = "Manual Close"
    PARTIAL_CLOSE = "Partial Close"
    STOP_LOSS = "Stop Loss"
    TAKE_PROFIT = "Take Profit"
    LIQUIDATION = "Liquidation"
    BREACH = "Breach"
    COPY_CLOSE = "Copy Close"


class EngineMode(str, Enum):
    LIVE = "live"
    PAPER = "paper"
    MOCK = "mock"
    DRY_RUN = "dry-run"


@dataclass
class TradeSignal:
    """Trading signal generated by a strategy (e.g. OB + Demand)."""
    symbol: str
    direction: OrderDirection
    sub_strategy_name: str
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ContractDetail:
    """Symbol specifications and risk limits from PropDAO."""
    symbol: str
    coin: str
    price_unit: float = 0.01
    price_precision: int = 2
    lot_step: float = 0.001
    sz_decimals: int = 3
    max_leverage: float = 2.0
    maker_fee_rate: float = 0.00015   # 0.015%
    taker_fee_rate: float = 0.00045   # 0.045%


@dataclass
class Position:
    """An open isolated-margin position on PropDAO."""
    id: str
    symbol: str
    side: OrderSide
    qty: float
    entry: float
    leverage: float
    notional: float
    margin_allocated: float
    opened_at: int
    mark: float
    unrealized_pnl: float
    sl: Optional[float] = None          # Gross USD PnL at trigger or price
    tp: Optional[float] = None          # Gross USD PnL at trigger or price
    sl_price: Optional[float] = None    # Actual stop-loss price
    tp_price: Optional[float] = None    # Actual take-profit price

    @property
    def margin(self) -> float:
        """Alias for margin_allocated or calculated margin collateral."""
        if hasattr(self, "margin_allocated") and self.margin_allocated > 0:
            return self.margin_allocated
        return (self.qty * self.entry) / (self.leverage or 1.0)

    @property
    def liquidation_price(self) -> float:
        """Isolated margin liquidation price: 100 / leverage % adverse move."""
        if self.leverage <= 1.0:
            return 0.0 if self.side == OrderSide.BUY else float("inf")
        pct_move = 1.0 / self.leverage
        if self.side == OrderSide.BUY:
            return max(0.0, self.entry * (1.0 - pct_move))
        else:
            return self.entry * (1.0 + pct_move)


@dataclass
class Order:
    """Resting, triggered, or completed order."""
    id: str
    symbol: str
    side: OrderSide
    qty: float
    order_type: OrderType
    limit_px: Optional[float] = None
    trigger_price: Optional[float] = None
    leverage: float = 1.0
    sl: Optional[float] = None
    tp: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: int = 0
    intent_id: Optional[str] = None
    tif: TimeInForce = TimeInForce.GTC
    reduce_only: bool = False
    filled_qty: float = 0.0
    remaining_qty: float = 0.0


@dataclass
class RiskState:
    """Live account risk assessment directly from GET /accounts/:id/risk."""
    equity: float
    balance: float
    floor: float
    floor_kind: str             # "max" or "daily"
    max_floor: float
    daily_floor: float
    room_usd: float             # equity - floor. The entire risk budget available.
    room_pct: float             # roomUsd as % of equity
    breached: bool
    open_positions: int = 0


@dataclass
class TradeOutcome:
    """Historical completed trade record."""
    trade_id: int | str
    symbol: str
    direction: OrderDirection
    entry_price: float
    exit_price: float
    quantity: float
    leverage: float
    open_time: float
    close_time: float
    realized_pnl_usdc: float
    gross_pnl: float
    fee: float
    open_fee: float = 0.0
    close_fee: float = 0.0
    exit_reason: str = "Manual Close"
    exit_liquidity: str = "taker"
    slippage_pct: float = 0.0
    smc_zone_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def realized_pnl(self) -> float:
        """Alias for realized_pnl_usdc."""
        return self.realized_pnl_usdc

    @property
    def realized_pnl_usdt(self) -> float:
        """Alias for compatibility with legacy reporting."""
        return self.realized_pnl_usdc

    @property
    def duration_seconds(self) -> float:
        """Duration of trade in seconds."""
        if self.close_time and self.open_time:
            return max(0.0, self.close_time - self.open_time)
        return 0.0

    @property
    def roe_percentage(self) -> float:
        """Return on Equity (Margin) percentage."""
        margin = (self.entry_price * self.quantity) / max(1.0, self.leverage)
        if margin > 0:
            return (self.realized_pnl_usdc / margin) * 100.0
        return 0.0


@dataclass
class AccountState:
    """Full account state representation."""
    account_id: str
    status: AccountStatus
    stage: Stage
    balance: float
    starting_balance: float
    daily_anchor_equity: float
    max_drawdown_limit_pct: float = 5.0
    daily_drawdown_limit_pct: float = 2.0
    profit_target_pct: float = 10.0
    drawdown_breached_at: Optional[int] = None
    open_positions: List[Position] = field(default_factory=list)
    pending_orders: List[Order] = field(default_factory=list)
    twap_orders: List[Dict[str, Any]] = field(default_factory=list)
    trade_history: List[Dict[str, Any]] = field(default_factory=list)
